/* /js/tinymce/langs/cs.js */
tinymce.addI18n('cs', {
  // Menubar
  "File": "Soubor",
  "Edit": "Úpravy",
  "View": "Zobrazení",
  "Insert": "Vložit",
  "Format": "Formát",
  "Tools": "Nástroje",
  "Table": "Tabulka",
  "Help": "Nápověda",

  // Základní ovládací prvky
  "Ok": "OK",
  "Cancel": "Zrušit",
  "Close": "Zavřít",
  "Save": "Uložit",
  "Undo": "Zpět",
  "Redo": "Znovu",
  "Cut": "Vyjmout",
  "Copy": "Kopírovat",
  "Paste": "Vložit",
  "Paste as text": "Vložit jako prostý text",
  "Select all": "Vybrat vše",
  "New document": "Nový dokument",
  "Remove": "Odstranit",
  "Delete": "Smazat",
  "Are you sure you want to do this?": "Opravdu to chcete provést?",
  "Something went wrong.": "Něco se pokazilo.",
  "Reveal or hide additional toolbar items": "Další nastavení",
  "words": "Slov",
  "Press Alt+0 for help": "Zmáčkni Alt+0 pro nápovědu",

  // Blocks / Nadpisy
  "Blocks": "Nadpisy",
  "Paragraph": "Odstavec",
  "Heading 1": "Nadpis 1",
  "Heading 2": "Nadpis 2",
  "Heading 3": "Nadpis 3",
  "Heading 4": "Nadpis 4",
  "Heading 5": "Nadpis 5",
  "Heading 6": "Nadpis 6",
  "Preformatted": "Předformátovaný",
  "Blockquote": "Citace",

  // Formátování
  "Bold": "Tučné",
  "Italic": "Kurzíva",
  "Underline": "Podtržené",
  "Strikethrough": "Přeškrtnuté",
  "Superscript": "Horní index",
  "Subscript": "Dolní index",
  "Clear formatting": "Vymazat formátování",
  "Remove format": "Odstranit formátování",

  // Barvy / fonty (pokud použiješ příslušná tlačítka)
  "Text color": "Barva textu",
  "Background color": "Barva pozadí",
  "Remove color": "Odstranit barvu",
  "Font family": "Písmo",
  "Font sizes": "Velikost písma",
  "Fonts": "Písmo",

  // Zarovnání / odsazení
  "Align": "Zarovnání",
  "Align left": "Zarovnat vlevo",
  "Align center": "Zarovnat na střed",
  "Align right": "Zarovnat vpravo",
  "Justify": "Zarovnat do bloku",
  "Outdent": "Zmenšit odsazení",
  "Indent": "Zvětšit odsazení",
  "Line height": "Výška řádku",
  "Color Picker": "Výběr barvy",

  // Seznamy
  "Bullet list": "Odrážkový seznam",
  "Numbered list": "Číslovaný seznam",

  // Odkazy
  "Link": "Odkaz",
  "Insert/edit link": "Vložit/upravit odkaz",
  "Insert link": "Vložit odkaz",
  "Open link": "Otevřít odkaz",
  "Open link in...": "Otevřít odkaz v...",
  "Open link in new tab": "Otevřít odkaz v nové záložce",
  "Current window": "Aktuální okno",
  "New window": "Nové okno",
  "Text to display": "Text odkazu",
  "Display text": "Text",
  "Url": "URL adresa",
  "Target": "Cíl odkazu",
  "Title": "Titulek",
  "Rel": "Vztah (rel)",
  "Remove link": "Odstranit odkaz",
  "Link options": "Možnosti odkazu",
  "No link": "Žádný odkaz",

  // Obrázky
  "Image": "Obrázek",
  "Image...": "Obrázek",
  "Link...": "Odkaz",
  "Insert/edit image": "Vložit/upravit obrázek",
  "Insert image": "Vložit obrázek",
  "Source": "Zdroj",
  "Image title": "Titulek obrázku",
  "Description": "Popis",
  "Alternative description": "Alternativní popis",
  "Image description": "Popis obrázku",
  "Dimensions": "Rozměry",
  "Width": "Šířka",
  "Height": "Výška",
  "Constrain proportions": "Zachovat poměr stran",
  "Caption": "Titulek pod obrázkem",
  "Image options": "Možnosti obrázku",
  "Browse files": "Procházet soubory",
  "Upload": "Nahrát",
  "Drop an image here": "Přetáhněte obrázek sem",

  // Média (pokud použiješ plugin media)
  "Media": "Médium",
  "Insert/edit media": "Vložit/upravit médium",
  "Embed": "Vložený kód",
  "Poster": "Náhledový obrázek",
  "Alternative source": "Alternativní zdroj",

  // Tabulky
  "Insert table": "Vložit tabulku",
  "Table properties": "Vlastnosti tabulky",
  "Row properties": "Vlastnosti řádku",
  "Cell properties": "Vlastnosti buňky",
  "Row": "Řádek",
  "Column": "Sloupec",
  "Cell": "Buňka",
  "Header cell": "Záhlaví buňky",
  "Scope": "Rozsah",
  "Row type": "Typ řádku",
  "Header": "Záhlaví",
  "Body": "Tělo",
  "Footer": "Zápatí",
  "Insert row before": "Vložit řádek před",
  "Insert row after": "Vložit řádek za",
  "Insert column before": "Vložit sloupec před",
  "Insert column after": "Vložit sloupec za",
  "Delete row": "Smazat řádek",
  "Delete column": "Smazat sloupec",
  "Delete table": "Smazat tabulku",
  "Merge cells": "Sloučit buňky",
  "Split cell": "Rozdělit buňku",
  "Cut row": "Vyjmout řádek",
  "Copy row": "Kopírovat řádek",
  "Paste row before": "Vložit řádek před",
  "Paste row after": "Vložit řádek za",
  "Table caption": "Titulek tabulky",

  // Hledání / nahrazování
  "Search": "Hledat",
  "Find": "Najít",
  "Replace": "Nahradit",
  "Find and replace": "Najít a nahradit",
  "Find next": "Najít další",
  "Find previous": "Najít předchozí",
  "Replace all": "Nahradit vše",
  "Match case": "Rozlišovat velikost písmen",
  "Whole words": "Pouze celá slova",

  // Zobrazení / nástroje
  "Code": "Kód",
  "Source code": "Zdrojový kód",
  "Visual blocks": "Vizualizovat bloky",
  "Visual aids": "Pomocné prvky",
  "Fullscreen": "Celá obrazovka",
  "Preview": "Náhled",
  "Print": "Tisk",
  "Print...": "Tisk",
  "Special character...": "Speciální znaky",
  "Anchor...": "Záložka",
  "Nonbreaking space": "Nezlomitelná mezera",
  "Special character": "Speciální znak",
  "Emoticons": "Emotikony",
  "Anchor": "Záložka",
  "Insert date/time": "Vložit datum/čas",
  "Horizontal line": "Vodorovná čára",
  "HR": "Oddělovač",
  "Page break": "Zlom stránky",
  "Date/time": "Datum/čas",
  "Show blocks": "Zobrazení bloků",
  "Find and replace...": "Najít a nahradit",
  "Formats": "Formát",
  "Headings": "Nadpisy",

  // Quickbars / nápověda / statistiky
  "Quick Link": "Rychlý odkaz",
  "Keyboard Shortcuts": "Klávesové zkratky",
  "Help": "Nápověda",
  "Words": "Slova",
  "Characters": "Znaky",
  "Paragraphs": "Odstavce",
  "Reading time": "Čas čtení"
});
